services:
  node-server:
    build: .
    ports:
      - 5000:3000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/website-db
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: {}