services:
  node-server:
    build: .
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - ${PORT}:3000
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: {}